# Import & summarize data

### Objectives:
First step will be exploring and understanding the new dataset.

Initial checklist:
1) shape of dataset
2) data types of features
3) missing values by column
4) column distributions
5) geographic distribution
6) time distribution
7) etc.

In [12]:
import pandas as pd
import numpy as np

In [13]:
train = pd.read_csv('../train.csv')

In [26]:
# show all 28 columns
pd.set_option('display.max_columns', 999)
train.head(5)

,RowId,IntersectionId,Latitude,Longitude,EntryStreetName,ExitStreetName,EntryHeading,ExitHeading,Hour,Weekend,Month,Path,TotalTimeStopped_p20,TotalTimeStopped_p40,TotalTimeStopped_p50,TotalTimeStopped_p60,TotalTimeStopped_p80,TimeFromFirstStop_p20,TimeFromFirstStop_p40,TimeFromFirstStop_p50,TimeFromFirstStop_p60,TimeFromFirstStop_p80,DistanceToFirstStop_p20,DistanceToFirstStop_p40,DistanceToFirstStop_p50,DistanceToFirstStop_p60,DistanceToFirstStop_p80,City
0,1920335,0,33.79166,-84.43003,Marietta Boulevard Northwest,Marietta Boulevard Northwest,NW,NW,0,0,6,Marietta Boulevard Northwest_NW_Marietta Boule...,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,Atlanta
1,1920336,0,33.79166,-84.43003,Marietta Boulevard Northwest,Marietta Boulevard Northwest,SE,SE,0,0,6,Marietta Boulevard Northwest_SE_Marietta Boule...,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,Atlanta
2,1920337,0,33.79166,-84.43003,Marietta Boulevard Northwest,Marietta Boulevard Northwest,NW,NW,1,0,6,Marietta Boulevard Northwest_NW_Marietta Boule...,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,Atlanta
3,1920338,0,33.79166,-84.43003,Marietta Boulevard Northwest,Marietta Boulevard Northwest,SE,SE,1,0,6,Marietta Boulevard Northwest_SE_Marietta Boule...,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,Atlanta
4,1920339,0,33.79166,-84.43003,Marietta Boulevard Northwest,Marietta Boulevard Northwest,NW,NW,2,0,6,Marietta Boulevard Northwest_NW_Marietta Boule...,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,Atlanta

In [28]:
# summary statistics to learn about the distribution of each column
train.describe().round(1)

,RowId,IntersectionId,Latitude,Longitude,Hour,Weekend,Month,TotalTimeStopped_p20,TotalTimeStopped_p40,TotalTimeStopped_p50,TotalTimeStopped_p60,TotalTimeStopped_p80,TimeFromFirstStop_p20,TimeFromFirstStop_p40,TimeFromFirstStop_p50,TimeFromFirstStop_p60,TimeFromFirstStop_p80,DistanceToFirstStop_p20,DistanceToFirstStop_p40,DistanceToFirstStop_p50,DistanceToFirstStop_p60,DistanceToFirstStop_p80
count,857409.0,857409.0,857409.0,857409.0,857409.0,857409.0,857409.0,857409.0,857409.0,857409.0,857409.0,857409.0,857409.0,857409.0,857409.0,857409.0,857409.0,857409.0,857409.0,857409.0,857409.0,857409.0
mean,2349039.0,836.3,39.7,-77.9,12.4,0.3,9.1,1.7,5.4,7.7,11.9,22.9,3.1,9.1,12.6,18.8,34.0,6.6,19.9,28.3,43.3,81.9
std,247512.8,644.2,2.9,6.0,6.1,0.4,2.0,7.1,12.9,15.6,19.6,28.1,11.6,20.1,23.8,29.4,40.6,28.0,56.6,71.7,96.9,152.7
min,1920335.0,0.0,33.6,-87.8,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,2134687.0,306.0,39.9,-84.4,8.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50%,2349039.0,685.0,40.0,-75.2,13.0,0.0,9.0,0.0,0.0,0.0,0.0,16.0,0.0,0.0,0.0,0.0,27.0,0.0,0.0,0.0,0.0,60.4
75%,2563391.0,1254.0,41.9,-75.1,17.0,1.0,11.0,0.0,0.0,10.0,19.0,35.0,0.0,0.0,22.0,31.0,49.0,0.0,0.0,52.9,64.1,85.6
max,2777743.0,2875.0,42.4,-71.0,23.0,1.0,12.0,273.0,318.0,343.0,368.0,689.0,334.0,347.0,355.0,358.0,359.0,1902.7,3099.5,3099.5,3581.6,4064.3

In [16]:
# 857,409 rows, 28 columns
train.shape

(857409, 28)

In [29]:
# counting missing values by column
# DataFrame.isna() and DataFrame.isnull() are the exact same 
train.isna().sum()

#takeaway: missing values only occur as Street Names (mostly as Entry Street Names)

RowId                         0
IntersectionId                0
Latitude                      0
Longitude                     0
EntryStreetName            8189
ExitStreetName             5534
EntryHeading                  0
ExitHeading                   0
Hour                          0
Weekend                       0
Month                         0
Path                          0
TotalTimeStopped_p20          0
TotalTimeStopped_p40          0
TotalTimeStopped_p50          0
TotalTimeStopped_p60          0
TotalTimeStopped_p80          0
TimeFromFirstStop_p20         0
TimeFromFirstStop_p40         0
TimeFromFirstStop_p50         0
TimeFromFirstStop_p60         0
TimeFromFirstStop_p80         0
DistanceToFirstStop_p20       0
DistanceToFirstStop_p40       0
DistanceToFirstStop_p50       0
DistanceToFirstStop_p60       0
DistanceToFirstStop_p80       0
City                          0
dtype: int64

In [30]:
train_na = train[train['EntryStreetName'].isna()]
train_na.head(50)

,RowId,IntersectionId,Latitude,Longitude,EntryStreetName,ExitStreetName,EntryHeading,ExitHeading,Hour,Weekend,Month,Path,TotalTimeStopped_p20,TotalTimeStopped_p40,TotalTimeStopped_p50,TotalTimeStopped_p60,TotalTimeStopped_p80,TimeFromFirstStop_p20,TimeFromFirstStop_p40,TimeFromFirstStop_p50,TimeFromFirstStop_p60,TimeFromFirstStop_p80,DistanceToFirstStop_p20,DistanceToFirstStop_p40,DistanceToFirstStop_p50,DistanceToFirstStop_p60,DistanceToFirstStop_p80,City
381,1920716,0,33.79166,-84.43003,NaN,Marietta Boulevard Northwest,NE,SE,4,0,10,Unknown_NE_Marietta Boulevard Northwest_SE,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,Atlanta
4033,1924368,10,33.65287,-84.39762,NaN,Porsche Avenue,N,E,11,0,6,Unknown_N_Porsche Avenue_E,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,Atlanta
4034,1924369,10,33.65287,-84.39762,NaN,Porsche Avenue,N,W,11,0,6,Unknown_N_Porsche Avenue_W,0,0,6,15,21,0,0,11,21,27,0.0,0.0,50.0,51.6,52.6,Atlanta
4043,1924378,10,33.65287,-84.39762,NaN,Porsche Avenue,N,E,18,0,6,Unknown_N_Porsche Avenue_E,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,Atlanta
4044,1924379,10,33.65287,-84.39762,NaN,Porsche Avenue,N,E,19,0,6,Unknown_N_Porsche Avenue_E,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,Atlanta
4063,1924398,10,33.65287,-84.39762,NaN,Porsche Avenue,N,E,17,0,7,Unknown_N_Porsche Avenue_E,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,Atlanta
4070,1924405,10,33.65287,-84.39762,NaN,Porsche Avenue,N,W,8,0,8,Unknown_N_Porsche Avenue_W,0,15,15,24,35,0,21,21,34,41,0.0,48.4,48.4,54.1,56.0,Atlanta
4084,1924419,10,33.65287,-84.39762,NaN,Porsche Avenue,N,E,16,0,8,Unknown_N_Porsche Avenue_E,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,Atlanta
4095,1924430,10,33.65287,-84.39762,NaN,Porsche Avenue,N,W,8,0,9,Unknown_N_Porsche Avenue_W,6,7,21,28,34,15,16,26,34,42,48.7,51.9,52.4,52.7,59.3,Atlanta
4100,1924435,10,33.65287,-84.39762,NaN,Porsche Avenue,N,E,11,0,9,Unknown_N_Porsche Avenue_E,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,Atlanta
4116,1924451,10,33.65287,-84.39762,NaN,Porsche Avenue,N,E,11,0,10,Unknown_N_Porsche Avenue_E,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,Atlanta
4124,1924459,10,33.65287,-84.39762,NaN,Porsche Avenue,N,E,15,0,10,Unknown_N_Porsche Avenue_E,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,Atlanta
4127,1924462,10,33.65287,-84.39762,NaN,Porsche Avenue,N,W,16,0,10,Unknown_N_Porsche Avenue_W,0,0,9,9,44,0,0,15,17,50,0.0,0.0,53.7,55.6,55.9,Atlanta
4144,1924479,10,33.65287,-84.39762,NaN,Porsche Avenue,N,E,10,0,11,Unknown_N_Porsche Avenue_E,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,Atlanta
4149,1924484,10,33.65287,-84.39762,NaN,Porsche Avenue,N,E,12,0,11,Unknown_N_Porsche Avenue_E,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,Atlanta
4157,1924492,10,33.65287,-84.39762,NaN,Porsche Avenue,N,E,17,0,11,Unknown_N_Porsche Avenue_E,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,Atlanta
4176,1924511,10,33.65287,-84.39762,NaN,Porsche Avenue,N,E,15,0,12,Unknown_N_Porsche Avenue_E,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,Atlanta
8399,1928734,32,33.77278,-84.42508,NaN,Marietta Boulevard Northwest,N,NW,15,0,6,Unknown_N_Marietta Boulevard Northwest_NW,0,22,38,43,57,0,36,53,55,74,0.0,69.6,72.0,74.5,87.1,Atlanta
8405,1928740,32,33.77278,-84.42508,NaN,Marietta Boulevard Northwest,N,NW,16,0,6,Unknown_N_Marietta Boulevard Northwest_NW,16,33,41,49,55,32,59,62,65,87,64.9,66.3,67.4,68.5,405.7,Atlanta
8464,1928799,32,33.77278,-84.42508,NaN,Donald Lee Hollowell Parkway Northwest,N,SW,7,0,7,Unknown_N_Donald Lee Hollowell Parkway Northwe...,0,19,28,34,90,0,41,45,48,101,0.0,63.3,64.6,65.4,77.9,Atlanta
8466,1928801,32,33.77278,-84.42508,NaN,Marietta Boulevard Northwest,N,NW,8,0,7,Unknown_N_Marietta Boulevard Northwest_NW,0,11,16,58,63,0,24,27,67,72,0.0,66.3,71.4,85.8,98.7,Atlanta
8483,1928818,32,33.77278,-84.42508,NaN,Marietta Boulevard Northwest,N,NW,15,0,7,Unknown_N_Marietta Boulevard Northwest_NW,25,59,59,62,80,35,71,71,81,108,69.3,71.4,71.4,71.5,76.2,Atlanta
8485,1928820,32,33.77278,-84.42508,NaN,Donald Lee Hollowell Parkway Northwest,N,E,16,0,7,Unknown_N_Donald Lee Hollowell Parkway Northwe...,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,Atlanta
8541,1928876,32,33.77278,-84.42508,NaN,Marietta Boulevard Northwest,N,NW,7,0,8,Unknown_N_Marietta Boulevard Northwest_NW,0,20,32,41,69,0,30,43,53,81,0.0,66.2,69.8,70.7,90.0,Atlanta
8552,1928887,32,33.77278,-84.42508,NaN,Donald Lee Hollowell Parkway Northwest,N,E,10,0,8,Unknown_N_Donald Lee Hollowell Parkway Northwe...,7,13,13,18,37,10,17,17,25,42,35.6,35.6,35.6,39.3,46.9,Atlanta
8554,1928889,32,33.77278,-84.42508,NaN,Donald Lee Hollowell Parkway Northwest,N,E,11,0,8,Unknown_N_Donald Lee Hollowell Parkway Northwe...,0,0,0,0,8,0,0,0,0,15,0.0,0.0,0.0,0.0,43.2,Atlanta
8591,1928926,32,33.77278,-84.42508,NaN,Donald Lee Hollowell Parkway Northwest,N,E,7,1,8,Unknown_N_Donald Lee Hollowell Parkway Northwe...,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,Atlanta
8630,1928965,32,33.77278,-84.42508,NaN,Donald Lee Hollowell Parkway Northwest,N,E,7,0,9,Unknown_N_Donald Lee Hollowell Parkway Northwe...,0,7,17,21,40,0,16,28,36,56,0.0,42.4,44.1,47.7,74.1,Atlanta
8631,1928966,32,33.77278,-84.42508,NaN,Marietta Boulevard Northwest,N,NW,7,0,9,Unknown_N_Marietta Boulevard Northwest_NW,0,35,42,45,76,0,49,54,62,87,0.0,70.6,71.9,74.5,91.0,Atlanta
8635,1928970,32,33.77278,-84.42508,NaN,Marietta Boulevard Northwest,N,NW,8,0,9,Unknown_N_Marietta Boulevard Northwest_NW,0,11,11,37,59,0,21,21,45,66,0.0,64.0,64.0,65.8,68.7,Atlanta
8646,1928981,32,33.77278,-84.42508,NaN,Marietta Boulevard Northwest,N,NW,15,0,9,Unknown_N_Marietta Boulevard Northwest_NW,30,33,33,35,79,38,44,44,46,85,66.3,67.6,67.6,73.6,76.8,Atlanta
8711,1929046,32,33.77278,-84.42508,NaN,Marietta Boulevard Northwest,N,NW,8,0,10,Unknown_N_Marietta Boulevard Northwest_NW,0,18,18,24,82,0,27,27,33,93,0.0,73.7,73.7,74.1,79.3,Atlanta
8721,1929056,32,33.77278,-84.42508,NaN,Donald Lee Hollowell Parkway Northwest,N,E,10,0,10,Unknown_N_Donald Lee Hollowell Parkway Northwe...,0,0,0,0,17,0,0,0,0,22,0.0,0.0,0.0,0.0,44.6,Atlanta
8725,1929060,32,33.77278,-84.42508,NaN,Donald Lee Hollowell Parkway Northwest,N,SW,11,0,10,Unknown_N_Donald Lee Hollowell Parkway Northwe...,0,0,24,54,67,0,0,33,60,75,0.0,0.0,55.2,56.9,61.4,Atlanta
8729,1929064,32,33.77278,-84.42508,NaN,Donald Lee Hollowell Parkway Northwest,N,E,13,0,10,Unknown_N_Donald Lee Hollowell Parkway Northwe...,0,0,0,11,14,0,0,0,17,20,0.0,0.0,0.0,43.7,43.8,Atlanta
8735,1929070,32,33.77278,-84.42508,NaN,Donald Lee Hollowell Parkway Northwest,N,E,15,0,10,Unknown_N_Donald Lee Hollowell Parkway Northwe...,0,0,0,0,34,0,0,0,0,43,0.0,0.0,0.0,0.0,60.1,Atlanta
8736,1929071,32,33.77278,-84.42508,NaN,Marietta Boulevard Northwest,N,NW,15,0,10,Unknown_N_Marietta Boulevard Northwest_NW,13,18,18,38,50,24,24,24,46,60,69.0,70.1,70.1,70.9,72.5,Atlanta
8802,1929137,32,33.77278,-84.42508,NaN,Donald Lee Hollowell Parkway Northwest,N,E,6,0,11,Unknown_N_Donald Lee Hollowell Parkway Northwe...,0,0,0,14,20,0,0,0,26,60,0.0,0.0,0.0,44.9,257.5,Atlanta
8807,1929142,32,33.77278,-84.42508,NaN,Donald Lee Hollowell Parkway Northwest,N,E,8,0,11,Unknown_N_Donald Lee Hollowell Parkway Northwe...,0,0,0,0,12,0,0,0,0,21,0.0,0.0,0.0,0.0,41.5,Atlanta
8809,1929144,32,33.77278,-84.42508,NaN,Marietta Boulevard Northwest,N,NW,10,0,11,Unknown_N_Marietta Boulevard Northwest_NW,0,7,17,17,44,0,18,25,26,82,0.0,66.2,68.4,75.1,75.9,Atlanta
8818,1929153,32,33.77278,-84.42508,NaN,Marietta Boulevard Northwest,N,NW,12,0,11,Unknown_N_Marietta Boulevard Northwest_NW,0,0,0,34,35,0,0,0,44,48,0.0,0.0,0.0,66.8,79.2,Atlanta
8828,1929163,32,33.77278,-84.42508,NaN,Donald Lee Hollowell Parkway Northwest,N,SW,17,0,11,Unknown_N_Donald Lee Hollowell Parkway Northwe...,33,33,42,65,66,43,43,94,102,113,58.6,66.9,76.6,259.5,268.8,Atlanta
8885,1929220,32,33.77278,-84.42508,NaN,Donald Lee Hollowell Parkway Northwest,N,SW,7,0,12,Unknown_N_Donald Lee Hollowell Parkway Northwe...,0,14,27,60,106,0,22,37,70,115,0.0,55.9,62.4,64.0,73.9,Atlanta
8890,1929225,32,33.77278,-84.42508,NaN,Donald Lee Hollowell Parkway Northwest,N,E,8,0,12,Unknown_N_Donald Lee Hollowell Parkway Northwe...,0,0,0,0,52,0,0,0,0,59,0.0,0.0,0.0,0.0,44.0,Atlanta
8894,1929229,32,33.77278,-84.42508,NaN,Donald Lee Hollowell Parkway Northwest,N,E,9,0,12,Unknown_N_Donald Lee Hollowell Parkway Northwe...,0,0,0,0,11,0,0,0,0,16,0.0,0.0,0.0,0.0,40.1,Atlanta
8898,1929233,32,33.77278,-84.42508,NaN,Donald Lee Hollowell Parkway Northwest,N,E,10,0,12,Unknown_N_Donald Lee Hollowell Parkway Northwe...,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,Atlanta
8902,1929237,32,33.77278,-84.42508,NaN,Donald Lee Hollowell Parkway Northwest,N,E,11,0,12,Unknown_N_Donald Lee Hollowell Parkway Northwe...,0,0,0,0,6,0,0,0,0,14,0.0,0.0,0.0,0.0,58.6,Atlanta
8910,1929245,32,33.77278,-84.42508,NaN,Donald Lee Hollowell Parkway Northwest,N,E,13,0,12,Unknown_N_Donald Lee Hollowell Parkway Northwe...,0,0,0,7,13,0,0,0,14,21,0.0,0.0,0.0,41.7,43.4,Atlanta
8911,1929246,32,33.77278,-84.42508,NaN,Marietta Boulevard Northwest,N,NW,13,0,12,Unknown_N_Marietta Boulevard Northwest_NW,0,26,29,49,52,0,35,36,56,61,0.0,65.2,69.5,70.2,73.4,Atlanta
10863,1931198,44,33.79901,-84.37049,NaN,Monroe Drive Northeast,NE,NW,11,0,6,Unknown_NE_Monroe Drive Northeast_NW,0,0,11,13,17,0,0,17,22,25,0.0,0.0,45.4,50.8,50.9,Atlanta

In [47]:
train.nunique()
#Takeaways: 
    # 2,539 intersections in the dataset
    # 4 cities confirmed 
    # only 9 months included

train.groupby('City').count()

# entries by city:
    # Atlanta: 153,363 rows
    # Boston:  182,050 rows
    # Chicago: 133,674 rows
    # Philly:  388,322 rows

,RowId,IntersectionId,Latitude,Longitude,EntryStreetName,ExitStreetName,EntryHeading,ExitHeading,Hour,Weekend,Month,Path,TotalTimeStopped_p20,TotalTimeStopped_p40,TotalTimeStopped_p50,TotalTimeStopped_p60,TotalTimeStopped_p80,TimeFromFirstStop_p20,TimeFromFirstStop_p40,TimeFromFirstStop_p50,TimeFromFirstStop_p60,TimeFromFirstStop_p80,DistanceToFirstStop_p20,DistanceToFirstStop_p40,DistanceToFirstStop_p50,DistanceToFirstStop_p60,DistanceToFirstStop_p80
City,,,,,,,,,,,,,,,,,,,,,,,,,,,
Atlanta,153363,153363,153363,153363,150231,150887,153363,153363,153363,153363,153363,153363,153363,153363,153363,153363,153363,153363,153363,153363,153363,153363,153363,153363,153363,153363,153363
Boston,182050,182050,182050,182050,180398,181052,182050,182050,182050,182050,182050,182050,182050,182050,182050,182050,182050,182050,182050,182050,182050,182050,182050,182050,182050,182050,182050
Chicago,133674,133674,133674,133674,132944,133018,133674,133674,133674,133674,133674,133674,133674,133674,133674,133674,133674,133674,133674,133674,133674,133674,133674,133674,133674,133674,133674
Philadelphia,388322,388322,388322,388322,385647,386918,388322,388322,388322,388322,388322,388322,388322,388322,388322,388322,388322,388322,388322,388322,388322,388322,388322,388322,388322,388322,388322